name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Запускается каждый день в полночь
  workflow_dispatch:     # Позволяет запустить вручную во вкладке Actions

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write    # Права, чтобы сохранить картинку

    steps:
      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output  # Картинки сохранятся в отдельную ветку 'output'
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
